### ISSUE TITLE
Exception thrown in app.UseMvc in .net core 1.1

### ISSUE THREAD

**Issue by ondravondra** [volosoft/castle-windsor-ms-adapter#1]
I am trying to use the library with Microsoft.AspNetCore.Mvc 1.1.0. With 1.0.0 it used to work fine, but when used with the new version it throws an exception at application startup. In `MvcApplicationBuilderExtensions.UseMvc(this IApplicationBuilder app, Action<IRouteBuilder> configureRoutes)`:

Exception thrown: 'Castle.MicroKernel.ComponentActivator.NoResolvableConstructorFoundException' in Castle.Windsor.dll

Additional information: Could not find resolvable constructor for Microsoft.AspNetCore.Mvc.DataAnnotations.Internal.MvcDataAnnotationsMvcOptionsSetup. Make sure all required dependencies are provided.

**Comment by hikalkan** [comment]
Thanks for reporting. I just started to upgrade to AspNet Core v1.1.

**Comment by ondravondra** [comment]
Thanks, it seems to be working now.
