### ISSUE TITLE
Can not release transient services if directly registered to the container

### ISSUE THREAD

**Issue by hikalkan** [volosoft/castle-windsor-ms-adapter#10]

**Comment by somintech** [comment]
Hi There, We are using MSdependency 1.0.0  will this solution work?

**Comment by hikalkan** [comment]
This release will be based on Microsoft.Extensions.DependencyInjection Version 1.1.0: https://github.com/volosoft/castle-windsor-ms-adapter/blob/rewrite/src/Castle.Windsor.MsDependencyInjection/Castle.Windsor.MsDependencyInjection.csproj#L34
