### ISSUE TITLE
Change .NET Standard dependency from Fortress.Windsor to Castle.Windsor 4.0.0

### ISSUE THREAD

**Issue by jonorossi** [volosoft/castle-windsor-ms-adapter#15]
We've now released Castle.Windsor 4.0.0 with .NET Standard support, you can now drop Fortress.Windsor which has been deprecated.

The other option is to just get `Castle.Windsor.Lifestyles.MSDependencyInjection` implemented which @fir3pho3nixx started on a branch.

**Comment by hikalkan** [comment]
Thanks a lot for the information. I will replace it soon.
