### ISSUE TITLE
Update to 5.0.0 version

### ISSUE THREAD

**Issue by totpero** [volosoft/castle-windsor-ms-adapter#43]
Hi,

You need to update the Castle.Core version to [5.0.0](https://github.com/castleproject/Core/releases/tag/v5.0.0)

The tests template project directly depends on [Castle.Core](https://github.com/aspnetboilerplate/module-zero-core-template/blob/master/aspnet-core/test/AbpCompanyName.AbpProjectName.Tests/AbpCompanyName.AbpProjectName.Tests.csproj#L32) and if you try to update all nugets to last version then the tests throw errors related to different Castle.Core version

**Comment by ismcagdas** [comment]
We need to wait for https://github.com/castleproject/Windsor/pull/613 because current Castle.Windsor 5.1.2 doesn't support Castle.Core 5.0.
