### ISSUE TITLE
Support .NET 4.5

### ISSUE THREAD

**Issue by vojtechvit** [volosoft/castle-windsor-ms-adapter#5]
Hi @hikalkan, great package! Do you think you could downgrade the required framework version to .NET 4.5? Our oldish systems (which use Windsor) are in that version and I'd really like to make them support packages with extension methods build for Microsoft's new IServiceCollection.

**Comment by hikalkan** [comment]
It already supports .net 4.5.2. If you are talking for .net 4.5.0, we don't want to support it since Microsoft also does not support it.
